### ISSUE TITLE
Splash Screen Implementation

### ISSUE THREAD

**Issue by Ora-Kool** [Ora-Kool/aad-team-6-animation-challenge#1]
The app should have a splash screen that give users first time intro of what they are about to see inside that app.

**Comment by KotlinGeekDev** [comment]
For that, I think instead of a splash screen, we can use a series of 'pages' to describe the features, and possibly, how to use the app.

**Comment by Ora-Kool** [comment]
Okay

**Comment by KotlinGeekDev** [comment]
Just like what the ViewPager library allows us to do.

**Comment by Ora-Kool** [comment]
I do understand what you are saying but can you handle this feature??

**Comment by KotlinGeekDev** [comment]
I will create a prototype and make a PR for for it for any suggestions/improvements.

**Comment by KotlinGeekDev** [comment]
Please, is there a way for me to obtain the app logo? I may need to use it.

**Comment by Ora-Kool** [comment]
The splash screen is working but there are bugs you have to really check

- The splash screen should be full screen

- You should make sure that when the splash screen start the next activity it should call finish()

**Comment by KotlinGeekDev** [comment]
Ok team lead. Noted.
So, for the first point, I can implement some kind of logo scaling, am I right?
