### ISSUE TITLE
Fix issues with .gitignore file

### ISSUE THREAD

**Issue by kkyb123** [Ora-Kool/aad-team-6-animation-challenge#12]
This is related to #5 
- I will like to use the .gitignore file found in https://github.com/github/gitignore/blob/master/Android.gitignore as the basic .gitignore file for the project. This is the standard .gitignore file propose by Github for android project
- I will also remove ignored files from the tracked files

**Comment by KotlinGeekDev** [comment]
@kkyb123 , I think that the only way to remove the .idea directory is, as an owner of the repo, to delete the directory. Read  #3 .

**Comment by kkyb123** [comment]
It is possible to remove the folder by removing it from tracked files then committing. However from this link https://github.com/github/gitignore/blob/master/Android.gitignore I now think it is not necessary to remove the whole folder but only some of the files in it that are not potable. That is what I will like to do.
I will like @AnonymousGeekDev to take part in the PR reviewing when I am done

**Comment by KotlinGeekDev** [comment]
I think this issue can be closed since it was solved.
