### ISSUE TITLE
Project Housekeeping

### ISSUE THREAD

**Issue by KotlinGeekDev** [Ora-Kool/aad-team-6-animation-challenge#3]
There is a folder in the project, .idea, which, according to what I researched and read, should not be present in GitHub repos. 
I will remove the folder first and make add/make changes to the .gitignore file in the project.
Any thoughts?

**Comment by Ora-Kool** [comment]
Okay, you can go ahead

**Comment by KotlinGeekDev** [comment]
Please, @Ora-Kool , It seems you are the only one who can delete the .idea idrectory from the repository.

**Comment by KotlinGeekDev** [comment]
OK. Issue is being solved by #12 . Closing...
