### ISSUE TITLE
DiaryApp needs a logo

### ISSUE THREAD

**Issue by Ora-Kool** [Ora-Kool/aad-team-6-animation-challenge#38]
Let someone come up with a logo for this project.

**Comment by LeoSammy** [comment]
I will like to do the logo for the app

**Comment by Ora-Kool** [comment]
![dairyapp_logo](https://user-images.githubusercontent.com/14142151/67279640-4e3e0c00-f4c3-11e9-8920-57bb8dcbddba.png)
I came up with that
