### ISSUE TITLE
Coupling the various UI

### ISSUE THREAD

**Issue by Ora-Kool** [Ora-Kool/aad-team-6-animation-challenge#9]
I wish to work on coupling the ui, connecting the version views with the java codes
I will be in charge to do so for all the views

**Comment by KotlinGeekDev** [comment]
Little question, team lead, should we switch to androidx namespace? On some newer android Studio builds, it seems to be a standard for projects(in my case, anyway).

**Comment by Ora-Kool** [comment]
Yes please
